### ISSUE TITLE
No error handling

### ISSUE THREAD

**Issue by metalwarrior665** [falkenbach/actor-glassdoor-jobs#2]
This actor crashes really easily, need to implement proper error handling.
https://my.apify.com/view/runs/Z69yzumcRnmk9FMSC

**Comment by falkenbach** [comment]
THanks, good point, will add error handling over weekend!

**Comment by falkenbach** [comment]
I added parsing termination in case if no results found and try-catch in order to provide log.error output in case of timeouts. Pls suggest if there is better way, the problem is that certain proxy groups partially blocked by glassdor - site still available but no actual search results returned. As the matter of fact only RESIDENTIAL group works reliable at my end.

**Comment by pocesar** [comment]
this is fixed in `beta`
